/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SelectSectionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  alwaysShowIcons: false,
  includeHeader: true,
  showSelectButton: true,
  showCopyButton: true
};
var SelectSectionPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.refreshBodyClass();
    this.registerEditorExtension(selectSectionExtension(this));
    this.registerMarkdownPostProcessor((element, context) => {
      const headers = element.querySelectorAll("h1, h2, h3, h4, h5, h6");
      headers.forEach((header) => {
        this.addIconsToHeader(header, context);
      });
    });
    this.addSettingTab(new SelectSectionSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFolder) {
          menu.addItem((item) => {
            item.setTitle("Merge Folder Notes").setIcon("documents").onClick(async () => {
              await this.mergeFolderNotes(file);
            });
          });
        }
      })
    );
  }
  async mergeFolderNotes(folder) {
    const files = folder.children.filter((file) => file instanceof import_obsidian.TFile && file.extension === "md").sort((a, b) => a.name.localeCompare(b.name));
    if (files.length === 0) {
      new import_obsidian.Notice("No markdown files found in this folder.");
      return;
    }
    let mergedContent = "";
    for (const file of files) {
      const content = await this.app.vault.read(file);
      if (mergedContent.length > 0) {
        mergedContent += "\n\n";
      }
      mergedContent += content;
    }
    let fileName = folder.name;
    let filePath = `${folder.path}/${fileName}.md`;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(filePath)) {
      filePath = `${folder.path}/${fileName} ${counter}.md`;
      counter++;
    }
    try {
      await this.app.vault.create(filePath, mergedContent);
      new import_obsidian.Notice(`Merged ${files.length} notes into ${filePath.split("/").pop()}`);
    } catch (error) {
      console.error("Error merging notes:", error);
      new import_obsidian.Notice("Failed to merge notes. See console for details.");
    }
  }
  onunload() {
    document.body.removeClass("select-section-always-show");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshBodyClass();
    this.app.workspace.updateOptions();
  }
  refreshBodyClass() {
    if (this.settings.alwaysShowIcons) {
      document.body.addClass("select-section-always-show");
    } else {
      document.body.removeClass("select-section-always-show");
    }
  }
  addIconsToHeader(header, context) {
    if (header.querySelector(".select-section-container"))
      return;
    const container = document.createElement("span");
    container.addClass("select-section-container");
    if (this.settings.showSelectButton) {
      const selectBtn = container.createSpan({ cls: "select-section-btn" });
      (0, import_obsidian.setIcon)(selectBtn, "mouse-pointer-click");
      selectBtn.ariaLabel = "Select and Copy Section";
      selectBtn.onclick = (e) => {
        e.stopPropagation();
        this.handleSelect(header, context);
      };
    }
    if (this.settings.showCopyButton) {
      const copyBtn = container.createSpan({ cls: "select-section-btn" });
      (0, import_obsidian.setIcon)(copyBtn, "copy");
      copyBtn.ariaLabel = "Copy Section";
      copyBtn.onclick = (e) => {
        e.stopPropagation();
        this.handleCopy(header, context);
      };
    }
    header.appendChild(container);
  }
  // Logic for Reading View Selection/Copy
  handleSelect(header, context) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view) {
      const sectionInfo = context.getSectionInfo(header);
      if (sectionInfo) {
        this.selectOrCopySection(view.editor, sectionInfo.lineStart, true);
      }
    }
  }
  handleCopy(header, context) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view) {
      const sectionInfo = context.getSectionInfo(header);
      if (sectionInfo) {
        this.selectOrCopySection(view.editor, sectionInfo.lineStart, false, true);
      }
    }
  }
  // Core Logic for Selection/Copy
  selectOrCopySection(editor, headerLine, select, copy = false) {
    const lineCount = editor.lineCount();
    const headerText = editor.getLine(headerLine);
    const match = headerText.match(/^(#+)\s/);
    if (!match)
      return;
    const level = match[1].length;
    let endLine = lineCount - 1;
    for (let i = headerLine + 1; i < lineCount; i++) {
      const line = editor.getLine(i);
      const nextMatch = line.match(/^(#+)\s/);
      if (nextMatch) {
        const nextLevel = nextMatch[1].length;
        if (nextLevel <= level) {
          endLine = i - 1;
          break;
        }
      }
    }
    let startLine = headerLine;
    if (!this.settings.includeHeader) {
      startLine++;
    }
    if (startLine > endLine) {
      if (this.settings.includeHeader) {
        endLine = startLine;
      } else {
        return;
      }
    }
    const rangeStart = { line: startLine, ch: 0 };
    const rangeEnd = { line: endLine, ch: editor.getLine(endLine).length };
    if (select) {
      editor.setSelection(rangeStart, rangeEnd);
      editor.scrollIntoView({ from: rangeStart, to: rangeEnd });
    }
    if (copy) {
      const textToCopy = editor.getRange(rangeStart, rangeEnd);
      navigator.clipboard.writeText(textToCopy).then(() => {
        new import_obsidian.Notice("Section copied to clipboard!");
      });
    }
  }
};
function selectSectionExtension(plugin) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        const builder = new import_state.RangeSetBuilder();
        for (const { from, to } of view.visibleRanges) {
          for (let pos = from; pos <= to; ) {
            const line = view.state.doc.lineAt(pos);
            const text = line.text;
            const match = text.match(/^(#+)\s/);
            if (match) {
              builder.add(
                line.to,
                line.to,
                import_view.Decoration.widget({
                  widget: new SelectSectionWidget(plugin, line.number - 1),
                  side: 1
                })
              );
            }
            pos = line.to + 1;
          }
        }
        return builder.finish();
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}
var SelectSectionWidget = class extends import_view.WidgetType {
  constructor(plugin, lineNumber) {
    super();
    this.plugin = plugin;
    this.lineNumber = lineNumber;
  }
  toDOM(view) {
    const container = document.createElement("span");
    container.addClass("select-section-container");
    container.addClass("cm-widget");
    if (this.plugin.settings.showSelectButton) {
      const selectBtn = container.createSpan({ cls: "select-section-btn" });
      (0, import_obsidian.setIcon)(selectBtn, "mouse-pointer-click");
      selectBtn.ariaLabel = "Select and Copy Section";
      selectBtn.onclick = (e) => {
        e.stopPropagation();
        const markdownView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          this.plugin.selectOrCopySection(markdownView.editor, this.lineNumber, true);
        }
      };
    }
    if (this.plugin.settings.showCopyButton) {
      const copyBtn = container.createSpan({ cls: "select-section-btn" });
      (0, import_obsidian.setIcon)(copyBtn, "copy");
      copyBtn.ariaLabel = "Copy Section";
      copyBtn.onclick = (e) => {
        e.stopPropagation();
        const markdownView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          this.plugin.selectOrCopySection(markdownView.editor, this.lineNumber, false, true);
        }
      };
    }
    return container;
  }
};
var SelectSectionSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Select and Copy Section Settings" });
    new import_obsidian.Setting(containerEl).setName("Always Show Icons").setDesc("If disabled, icons will only show when hovering over the header.").addToggle((toggle) => toggle.setValue(this.plugin.settings.alwaysShowIcons).onChange(async (value) => {
      this.plugin.settings.alwaysShowIcons = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Include Header in Selection").setDesc("If enabled, the header itself will be included in the selection/copy.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeHeader).onChange(async (value) => {
      this.plugin.settings.includeHeader = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Select Button").setDesc("Show the button to select the section content.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showSelectButton).onChange(async (value) => {
      this.plugin.settings.showSelectButton = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Copy Button").setDesc("Show the button to copy the section content.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showCopyButton).onChange(async (value) => {
      this.plugin.settings.showCopyButton = value;
      await this.plugin.saveSettings();
    }));
  }
};
